security:
    role_hierarchy:
        ROLE_WRITER: ROLE_USER
        ROLE_ADMIN: ROLE_WRITER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    
    providers:
        in_memory:
            memory:
                users:
                    root:
                        password: prouse5terdl123$
                        roles: 'ROLE_SUPER_ADMIN'
                    admin:
                        password: prouse5terdl123$
                        roles: 'ROLE_ADMIN'
                    writer:
                        password: writer123
                        roles: 'ROLE_WRITER'
                    user:
                        password: user123
                        roles: 'ROLE_USER'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
