security:
      access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/catalogue/node/item/resource, methods: [PATCH], roles: ROLE_WRITER, requires_channel: https }
        - { path: ^/, methods: [PATCH, POST], roles: ROLE_WRITER, requires_channel: https }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] , requires_channel: https }
