parameters:
  upload_directory: '%kernel.project_dir%/%env(resolve:UPLOADS_PARENT)%/uploads'
  upload_target_url: '/api/upload/'
  existing_uploads_url: '/catalogue/node/item/resources/'
  unfinished_uploads_url: '/api/upload/unfinished/'
  commit_upload_url: '/api/upload/commit'
  remove_upload_url: '/api/upload/remove'
  resource_url: '/catalogue/node/item/resource/'
  item_url: '/catalogue/node/item/'
  item_search_url: '/catalogue/search/items/'
  get_nodes_url: '/catalogue/nodes/'
  get_items_url: '/catalogue/node/items/'
  max_main_resources: 1
  max_additional_resources: 7
