parameters:
    locale: 'ru'
    upload_directory: '%kernel.project_dir%/public/uploads'
    upload_target_url: '/api/upload/'
    existing_uploads_url: '/catalogue/node/item/resources/'
    unfinished_uploads_url: '/api/upload/unfinished/'
    commit_upload_url: '/api/upload/commit'
    remove_upload_url: '/api/upload/remove'
    update_resource_url: '/catalogue/node/item/resource/'
    get_nodes_url: '/catalogue/nodes/'
    get_items_url: '/catalogue/node/items/'
    max_main_resources: 1
    max_additional_resources: 7

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,PhotoBank,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']




    # JSON Encoder
    app.encoder.json:
        class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'
    # XML Encoder
    app.encoder.xml:
        class: 'Symfony\Component\Serializer\Encoder\XmlEncoder'

    app.normalizer.catalogue.node:
        class: 'App\Serializer\Normalizer\CatalogueNodeNormalizer'

    app.normalizer.catalogue.item:
        class: 'App\Serializer\Normalizer\CatalogueNodeItemNormalizer'

    app.normalizer.resource:
        class: 'App\Serializer\Normalizer\ResourceNormalizer'

    App\Serializer\AppSerializer:
        autowire: false
        autoconfigure: false
        public: false
        arguments:
            0:
                - '@app.normalizer.catalogue.node'
                - '@app.normalizer.catalogue.item'
                - '@app.normalizer.resource'
                - '@serializer.normalizer.object'
            1:
                - '@app.encoder.json'
                - '@app.encoder.xml'
