services:
    App\PhotoBank\FileUploaderBundle\Controller\:
      autowire: true
      resource: '../../Controller'
      tags: ['controller.service_arguments']

    App\PhotoBank\FileUploaderBundle\Service\UploadReceiver:
      autowire: true
